config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  resources :projects do
    resources :feedbacks, only: :create do
      resources :replies, only: :create
      member do
        put "like", to: "feedbacks#like"
      end
    end
    member do
      put "like", to: "projects#like"
    end
  end
  
  devise_for :users

  resources :users, only: [:show]  do
    member do
      put "follow", to: "users#follow"
    end
  end

  get "predictions", to: "api#predictions"

  get "search", to: "searches#search"

  get "discover", to: "misc#discover"

  get "notifications", to: "activities#notifications"

  scope "/misc" do
    put "clearNotif", to: "misc#clearNotif"
    get "clearFirstTime", to: "misc#clearFirstTime"
    get "moreProjects", to: "searches#moreProjects"
    get "moreUsers", to: "searches#moreUsers"
  end

end

app/views/partials/_header.html.erb
<header>
  <div class="links">
    <%= link_to "Shift", root_path, :class=> "logo" %>
    <%= link_to "Discover", discover_path, :class=> "discover" %>
  </div>
  <% if user_signed_in? %>
    <div class="search">
      <%= form_tag("/search", method: "get", class: "search-form") do %>
        <%= text_field_tag :q, nil, class: "search-input", :placeholder => "Search", :autocomplete => "off" %>
        <%= submit_tag "", :class => "search-submit" %>
      <% end %>
      <div class="search-dropdown"></div>
    </div>
    <div class="person">
      <%= render "icons/notification" %>
      <% if @notifications.length == 0 %>
        <%= render "dropdowns/notification_first_time" %>
      <% else %>
        <%= render "dropdowns/notification" %>
      <% end %>
      <%= link_to current_user.name.split[0], current_user, :class=> "user" %>
      <%= render "icons/settings" %>
    </div>
  <% else %>
    <div class="not-logged-in">
      <%= link_to "Log in", new_user_session_path, :class => "log-in" %>
      <%= link_to "Sign up", new_user_registration_path, :class => "sign-up" %>
    </div>
  <% end %>
</header>