config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  resources :projects do
    resources :feedbacks, only: :create do
      resources :replies, only: :create
      member do
        put "like", to: "feedbacks#like"
      end
    end
    member do
      put "like", to: "projects#like"
    end
  end
  
  devise_for :users

  resources :users, only: [:show]  do
    member do
      put "follow", to: "users#follow"
    end
  end

  get "predictions", to: "api#predictions"

  get "search", to: "searches#search"

  get "discover", to: "misc#discover"

  get "notifications", to: "activities#notifications"

  scope "/misc" do
    put "clearNotif", to: "misc#clearNotif"
    get "clearFirstTime", to: "misc#clearFirstTime"
    get "moreProjects", to: "searches#moreProjects"
    get "moreUsers", to: "searches#moreUsers"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  include PublicActivity::Common

  MY_SALT = 'shift_lazandrei19'

  after_create :generate_hashed_id
  validates_uniqueness_of :hashed_id

  belongs_to :user
  has_many :feedbacks, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :members, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :logo
  validates_presence_of :headline
  validates_presence_of :description
  validates_presence_of :user

  validates_length_of :headline, :maximum => 140

  searchable do
    text :headline, :description, :name
  end

  acts_as_votable

  has_attached_file :logo, styles: { medium: "150x150#", thumb: "75x75#", mini: "50x50#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/

  accepts_nested_attributes_for :images, reject_if: proc { |attributes| attributes['image'].blank? }, allow_destroy: true

  def to_param
    self.hashed_id
  end

  private

  def generate_hashed_id
    self.update_attributes(:hashed_id => Digest::SHA1.hexdigest("--#{MY_SALT}--#{self.id}--")[0..15])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :like]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorized_user, only: [:edit, :update, :destroy]

  def like
    unless current_user.voted_for? @project
      @project.create_activity :like, owner: current_user, recipient: @project.user
      @project.create_activity :likeNotification, owner: current_user, recipient: @project.user

      @project.user.unread += 1
      @project.user.save

      @project.liked_by current_user
    else
      @activity = PublicActivity::Activity.find_by(trackable_id: (@project.id), key: "project.like")
      @activityNotification = PublicActivity::Activity.find_by(trackable_id: (@project.id), key: "project.likeNotification")
      @activity.destroy
      @activityNotification.destroy

      @project.user.unread -= 1
      @project.user.save

      @project.unliked_by current_user
    end

    redirect_to :back
  end

  def show
    @project.increment! :score
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      @project.create_activity :create, owner: current_user
      members[:members].chomp.split(/\n/).reject(&:empty?).uniq.each do |member|
        user_hashed_id = /\/users\/(\w{16})/.match(member)[1]
        user = User.find_by_hashed_id(user_hashed_id)
        if user
          member = user.members.create
          @project.members << member
        end
      end
      
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      @project.members.delete_all
      members[:members].each_line do |member|
        @project.members.create(:user => User.find_by_hashed_id(/\/users\/(\w{16})/.match(member)[1]))
      end
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    
    redirect_to projects_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find_by_hashed_id(params[:id])
    end

    # Check if the user has permissions to destroy/delete the entry
    def authorized_user
      @project = current_user.projects.find_by_hashed_id(params[:id])
      redirect_to projects_path, notice: "Not authorized to edit this project" if @project.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :logo, :headline, :description, images_attributes: [:id, :image, :_destroy])
    end
    
    def members
      params.require(:project).permit(:members)
    end
end

app/views/projects/_image_fields.html.erb
<div class="nested-fields">
  <%= f.input :image, input_html: { accept: "image/*" } %>
  <%= link_to_remove_association "remove image", f %>
</div>

app/views/projects/_project.html.erb
<h1><%= project.name %></h1>
<h4><%= project.headline %></h4>

app/views/projects/edit.html.erb
<%= simple_form_for(@project, html: { multipart: true, class: "new-project-form" }) do |f| %>

  <%= f.input :name, label: "How is your project called?" %>
  <%= f.input :headline, as: :text %>
  <%= f.input :logo %>
  <%= f.input :description %>
  <% members_paths = ''
     @project.members.each do |member|
       members_paths += request.base_url + user_path(member.user) + "\n"
     end
  %>
  <%= f.input :members, :as => :text, input_html: {value: members_paths, cols: 80, rows: 4} %>
  <h3>Images</h3>
  <%= f.simple_fields_for :images do |image| %>
    <%= render 'image_fields', f: image %>
  <% end %>
  <div>
    <%= link_to_add_association 'add image', f, :images %>
  </div>
  <%= f.button :submit %>
<% end %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Headline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.headline %></td>
        <td><%= link_to 'Show', project %></td>
        <% if project.user == current_user %>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div class="new-project">
  <div class="title">Add a new project</div>
  
  <%= simple_form_for(@project, html: { class: "new-project-form" }, defaults: { label_html: { class: "new-project-label" }, input_html: { class: "new-project-input" }, wrapper_html: { class: "new-project-wrapper" }, error: false }) do |f| %>

    <%= f.input :name, label: "How is your project called?", input_html: { class: "new-project-input new-project-input-name" } %>
    <%= f.input :headline, as: :text, label: "Present your project’s unique key selling phrase in 140 characters.", input_html: { maxlength: 140, cols: 50 }%>
    <%= f.input :logo, label: "Insert the logo of your project", input_html: { accept: "image/*", class: "new-project-input-logo" }, wrapper_html: { class: "new-project-wrapper-logo" } %>
    <label class="fake-logo-input" for="project_logo">Upload Logo</label>
    <%= f.input :description, input_html: { cols: 50 } %>
    <%= f.input :members, :as => :text, input_html: {value: "", cols: 50, rows: 4} %>
    <h3>Images</h3>
    <%= f.simple_fields_for :images do |image| %>
      <%= render 'image_fields', f: image %>
    <% end %>
    <div>
      <%= link_to_add_association 'add image', f, :images %>
    </div>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="project">
  <div class="info">
    <div class="logo">
      <%= image_tag(@project.logo.url(:medium), :class => "logo-image")%>
    </div>
    <div class="name"><%= @project.name %></div>
    <div class="headline"><%= @project.headline %></div>
  </div>
  <div class="description">
    <div class="description-headline">Product:</div>
    <div class="description-content">
      <% if strip_tags(md_render(@project.description)).length > 140 %>
        <% if @project.images.length > 0 %>
          <div class="carousel">
            <div class="image-carousel">
              <%= fa_icon "chevron-left", class: "arrow arrow-left" %>
              <%= fa_icon "chevron-right", class: "arrow arrow-right" %>
              <div class="carousel-images">
                <% @project.images.each do |image| %>
                  <div class="carousel-image-container">
                    <%= image_tag(image.image.url(:original), :class => "carousel-image") %>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="carousel-control">
              <% @project.images.each do |image| %>
                <div class="carousel-control-image-container">
                  <%= image_tag(image.image.url(:thumb), :class => "carousel-control-image") %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <span class="first140">
          <%= truncate(strip_tags(md_render(@project.description)), length: 140, omission: '', separator: ' ') %>
        </span>
        <span class="complete">
          <%= md_render @project.description %>
        </span>
        <div class="more">
          <%= link_to "+ More", "#", :class => "more-link" %>
        </div>
      <% elsif strip_tags(md_render(@project.description)).length <= 140 && @project.images.length > 0 %>
        <div class="carousel">
          <div class="image-carousel">
            <%= fa_icon "chevron-left", class: "arrow arrow-left" %>
            <%= fa_icon "chevron-right", class: "arrow arrow-right" %>
            <div class="carousel-images">
              <% @project.images.each do |image| %>
                <div class="carousel-image-container">
                  <%= image_tag(image.image.url(:original), :class => "carousel-image") %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="carousel-control">
            <% @project.images.each do |image| %>
              <div class="carousel-control-image-container">
                <%= image_tag(image.image.url(:thumb), :class => "carousel-control-image") %>
              </div>
            <% end %>
          </div>
        </div>
        <span class="first140">
          <%= strip_tags(md_render(@project.description)) %>
        </span>
        <div class="more">
          <%= link_to "+ More", "#", :class => "more-link" %>
        </div>
      <% else %>
        <span class="first140">
          <%= strip_tags(md_render(@project.description)) %>
        </span>
      <% end %>
    </div>
  </div>
  <div class="members">
    <div class="members-headline">Team:</div>
    <div class="members-content">
      <% @project.members.each_with_index do |member, index| %>
        <div class="member <%= index < 3 ? "not-hidden" : "hidden" %>">
          <div class="profile-photo">
            <%= image_tag(member.user.avatar.url(:thumb), :class => "profile-image") %>
          </div>
          <div class="text">
            <div class="name"><%= member.user.name %></div>
            <div class="workplace">
              <span class="company"><%= member.user.workplaces[0].company %></span>
              -
              <span class="position"><%= member.user.workplaces[0].position %></span>
            </div>
            <div class="appreciation">
              <%= member.user.appreciation || 0 %>
              <%= render "icons/heart" %>
            </div>
          </div>
        </div>
      <% end %>
      <% if @project.members.length > 3 %>
        <div class="more">
          <%= link_to "+ More", "#", :class => "more-link" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="feedback">
    <div class="project-appreciation">
      <%= link_to like_project_path, :method => :put do %>
        <%= render "icons/heart_like", like: (current_user.voted_for? @project) %>
      <% end %>
      <%= pluralize(@project.votes_for.size, "person") %>
      <%= like_or_likes(@project.votes_for.size) %>
      it. Do you?
    </div>
    <div class="feedback-headline">
      What others have said about
      <%= @project.name %>:
    </div>
    <div class="feedback-inputs">
      <%= simple_form_for [@project, Feedback.new], :html=> { class: "feedback-form" } do |f| %>
        <%= f.input :content, placeholder: "How can you help #{@project.name} and their team?", required: false, label: false, input_html: { class: "feedback-input" } %>
        <%= image_tag("/images/markdown.png", :class => "markdown-indicator") %>
        <%= f.button :submit, "Submit", class: "feedback-submit" %>
      <% end %>
    </div>
    <div class="feedbacks">
      <%= render @project.feedbacks %>
    </div>
  </div>
</div>
<div class="lightbox">
  <div class="bg"></div>
  <div class="image-container">
    <img class="lightbox-image">
  </div>
</div>