config/routes.rb
Rails.application.routes.draw do
  root 'activities#index'

  resources :projects do
    resources :feedbacks, only: :create do
      resources :replies, only: :create
      member do
        put "like", to: "feedbacks#like"
      end
    end
    member do
      put "like", to: "projects#like"
    end
  end
  
  devise_for :users

  resources :users, only: [:show]  do
    member do
      put "follow", to: "users#follow"
    end
  end

  get "predictions", to: "api#predictions"

  get "search", to: "searches#search"

  get "discover", to: "misc#discover"

  get "notifications", to: "activities#notifications"

  scope "/misc" do
    put "clearNotif", to: "misc#clearNotif"
    get "clearFirstTime", to: "misc#clearFirstTime"
    get "moreProjects", to: "searches#moreProjects"
    get "moreUsers", to: "searches#moreUsers"
  end

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  include PublicActivity::Common

  after_create :generate_hashed_id
  validates_uniqueness_of :hashed_id

  belongs_to :project
  belongs_to :user

  has_many :replies, dependent: :destroy

  acts_as_votable

  MY_SALT = 'shift_lazandrei19'

  def to_param
    self.hashed_id
  end

  validates_presence_of :content
  validates_presence_of :project
  validates_presence_of :user
  validates_associated :replies

  private

  def generate_hashed_id
    self.update_attributes(:hashed_id => Digest::SHA1.hexdigest("--#{MY_SALT}--#{self.id}--")[0..15])
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: :like
  before_action :authenticate_user!

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @project = Project.find_by_hashed_id(params[:project_id])
    @project.score += 5
    @project.save
    @feedback = @project.feedbacks.new(feedback_params)
    @feedback.user = current_user

    if @feedback.save
      @feedback.create_activity :create, owner: current_user, recipient: @feedback.project.user
      @feedback.create_activity :createNotification, owner: current_user, recipient: @feedback.project.user
      @feedback.project.user.unread += 1
      @feedback.project.user.save
      redirect_to @project
    else
      redirect_to @project
    end
  end

  def like
    unless current_user.voted_for? @feedback
      @feedback.liked_by current_user
      @feedback.create_activity :likeNotification, owner: current_user, recipient: @feedback.user
      @feedback.user.appreciation += 1
      @feedback.user.save
      @feedback.user.unread += 1
      @feedback.user.save
    else
      @activity = PublicActivity::Activity.find_by(trackable_id: (@feedback.id), key: "feedback.likeNotification", recipient_id: (@feedback.user.id))
      @activity.destroy
      @feedback.unliked_by current_user
      @feedback.user.appreciation -= 1
      @feedback.user.save
      @feedback.user.unread -= 1
      @feedback.user.save
    end
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find_by_hashed_id(params[:id])
    end

    # Check if the user has permissions to destroy/delete the entry
    def authorized_user
      @feedback = current_user.feedbacks.find_by_hashed_id(params[:id])
      redirect_to feedbacks_path, notice: "Not authorized to edit this feedback" if @feedback.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feedback_params
      params.require(:feedback).permit(:content)
    end
end

app/views/feedbacks/_feedback.html.erb
<div class="feedback-content">
  <div class="feedback-profile-photo">
    <%= image_tag(feedback.user.avatar.url(:thumb), :class => "feedback-profile-image") %>
  </div>
  <div class="appreciation">
    <%= link_to like_project_feedback_path(@project, feedback), :method => :put do %>
      <%= render "icons/heart_like", like: (current_user.voted_for? feedback)%>
    <% end %>
    <%= feedback.get_likes.size %>
  </div>
  <div class="feedback-text">
    <div class="feedback-user"><%= feedback.user.name %></div>
    <div class="feedback-content-text"><%= md_render feedback.content %></div>
  </div>
  <div class="reply">
    <%= render "icons/reply" %>
  </div>
</div>
<div class="replies">
  <%= render feedback.replies %>

  <%= simple_form_for [@project, feedback, Reply.new], :html=> { class: "reply-form" } do |f| %>
    <%= f.input :content, placeholder: "Reply to #{feedback.user.name.split[0]}", label: false, required: false, input_html: { class: "reply-form-input" } %>
    <%= f.button :submit, "Submit", class: "reply-form-submit" %>
  <% end %>
</div>